version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "49152-65535:49152-65535"
    restart: always

    volumes:
      - ./logs:/app/logs